export * from './Home'
export * from './SignUp'
export * from './Login'
export * from './Dashboard'
export * from './OnBoarding'
export * from '../features/ui/Noticias'
export * from '../features/ui/Equipo'
