export * from './Home'
export * from './SignUp'
export * from './Login'
export * from './Dashboard'
export * from './OnBoarding'
export * from './Dashboard/Chat'
export * from './Dashboard/Noticias'
export * from './Dashboard/Equipo'
